### PR TITLE
Update to fix examples ipynb files

### LINKED ISSUE #316: The example ipynb files have outdated modules
**Describe the bug**
The ipynb files in the examples folder use some outdated modules in numalogic in preprocessing section and etc

**To Reproduce**

1. Clone the git repository or download the exmples folder
2. Execute the cells in the quickstrat.ipynb to find the module not found error

**Expected behavior**
Able to run all cell in the example ipynb cells

**Screenshots**

**Environment (please complete the following information):**

local

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by haripriyajk**
This PR updates outdated modules being used n the python notebooks in the examples folder.

Fixes #316

### CODE REVIEW

**Comment by haripriyajk** [comment]
@s0nicboOm  @ab93 @nkoppisetty @qhuai please review this PR

**Review by s0nicboOm — CHANGES_REQUESTED** [review]
May I Know why did we remove `%load_ext autotime` ?

Also, can you rebase your PR? 

Otherwise looks good to me.

**Comment by haripriyajk** [comment]
> May I Know why did we remove `%load_ext autotime` ?
> I have removed it as its not present in quick_start.ipynb and I was not able to import it or install it without issues.I forgot to add it back before merging.Let me know if I should add it back.
> Also, can you rebase your PR?
> 
> Otherwise looks good to me.

**Review by s0nicboOm — APPROVED** [review]
LGTM!

**Comment by haripriyajk** [comment]
I see that the PR is has passed all the checks,can we  merge this?

**Pull request merged**
