### PR TITLE
added support for python@3.11

### PR DESCRIPTION
**Pull request by tcchawla**
Signed-off-by: tcchawla <tc.chawla2000@gmail.com>

Solves issue: #68 

Explain what this PR does.
- This PR adds support for latest python 3.11 version
- Changed workflow to support the latest version
- Changed project dependency to support 3.11.x versions

Let me know if any changes are required!

### CODE REVIEW

**Comment by ab93** [comment]
Thanks @tcchawla, however I don't think Pytorch currently supports 3.11: https://pypi.org/project/torch/  :( 
Let's keep an eye out, and the PR open. Will merge when they do support.

**Comment by tcchawla** [comment]
Hey @ab93, can we re-run the workflow tests to make sure the changes are working?

**Comment by vigith** [comment]
> Hey @ab93, can we re-run the workflow tests to make sure the changes are working?

I have rerun the workflow.

**Review by ab93 — CHANGES_REQUESTED** [review]
Hi @tcchawla could you sign your commits?

**Comment by tcchawla** [comment]
Hey @ab93, I have signed the commits.

**Review by ab93 — APPROVED** [review]
Looks good!

**Comment by tcchawla** [comment]
Hey @ab93, While resolving DCO check, there were many code conflicts, so I decided to open a new PR with same changes. Please review that, and close this one. Thanks for being patient with this small issue.

**Comment by ab93** [comment]
Sounds good @tcchawla !

**Pull request closed without merging**
